### ISSUE TITLE
Signification du "Version"

### ISSUE THREAD

**Issue by craberomantique** [AlexandreCARRON/AutoStack_Enterprise#1]
Dans ton fichier "docker-compose.yml" la ligne 1 `version: '3.1'` correspond en fait à la version du Docker Engine que l'on utilise sur la machine concernée. ;) 

![image](https://github.com/AlexandreCARRON/Odoo-v17_Automatic-deployement-services/assets/117639870/5512ba27-f915-432f-b534-1ab5d09972e9)

**Comment by AlexandreCARRON** [comment]
Merci mon ptit crabe romantique ^_^ Je commenterak la ligne avec la
commande pour identifier la version de docker engine ;)

Le sam. 17 févr. 2024 à 18:11, craberomantique ***@***.***> a
écrit :
